# # FROM python:3.11
# FROM python:3.11 
# COPY ./requirements.txt /workspaces/tributary/requirements.txt
# COPY ./entrypoint.py /workspaces/tributary/entrypoint.py 
# RUN pip install -r requirements.txt
# # copy /workspaces/tributary/entrypoint.py
# CMD exec gunicorn entrypoint:app


FROM python:3.11

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./entrypoint.py .
CMD exec gunicorn --bind 0.0.0.0:8000 entrypoint:app